import { UserData } from '../interfaces/Authentication';

export const userMockDg: UserData = {
  userId: 'VCHERNEY.EXT',
  nome: 'Volodymyr',
  cognome: 'Cherney',
  codiceFiscale: 'chrvdy88d17z138p',
  email: 'VCherney.ext@lavoro.gov.it',
  tipoAutenticazione: 'ad',
  numeroprofili: 0,
  profiloCorrente: null,
  spidIndirizzo: '',
  spidExpirationDate: '',
  spidEmail: '',
  spidMobilePhone: '',
  spidNumeroDocumento: '',
  spidDataNascita: '',
  spidCodiceLuogoDiNascita: '',
  spidStatoNascita: '',
  spidSesso: '',
  gruppiAD: [
    '[MDM]DGTS-ABILITAZIONECPM',
    'UtenteActiveDirectory',
    'UtenteHelpDesk',
    '[MDM]AmminisHelpdeskLDue',
    '[MDM]Helpdesk',
  ],
  officeAD: 'Personale Esterno',
  haUnicaDelegaInAssoluto: false,
  iS_AD_USER: false,
  ruoli: [],
  jwtToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVm9sb2R5bXlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6IkNoZXJuZXkiLCJhZEdydXBwaSI6WyJbTURNXURHVFMtQUJJTElUQVpJT05FQ1BNIiwiVXRlbnRlQWN0aXZlRGlyZWN0b3J5IiwiVXRlbnRlSGVscERlc2siLCJbTURNXUFtbWluaXNIZWxwZGVza0xEdWUiLCJbTURNXUhlbHBkZXNrIl0sImFkT2ZmaWNlIjoiUGVyc29uYWxlIEVzdGVybm8iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlZDSEVSTkVZLkVYVCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IlZDaGVybmV5LmV4dEBsYXZvcm8uZ292Lml0IiwiY29kaWNlZmlzY2FsZSI6ImNocnZkeTg4ZDE3ejEzOHAiLCJudW1lcm9Qcm9maWxpIjoiMCIsInRpcG9hQXRlbnRpY2F6aW9uZSI6ImFkIiwiaXNBRFVzZXIiOiJUcnVlIiwiaXNIRFVzZXIiOiJUcnVlIiwiaXNDaWVVc2VyIjoiRmFsc2UiLCJqdGkiOiI0NWVhZmRmYi1hNDI3LTRjNWEtYjIwNC04ODgyNWUwYjkzYTgiLCJleHAiOjE3MjE5ODQ4NTYsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3QiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.rlidQgUMe_IVEcjCrUSyjmDrpea0fNAfKx6DyxzWyd0',
  jwtTokenExpire: '2024-07-26T09:07:36Z',
  profiliUtente: null,
};
